DROP TABLE IF EXISTS roles_privileges;
DROP TABLE IF EXISTS users_roles;
DROP TABLE IF EXISTS privilege;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
  ID INT NOT NULL AUTO_INCREMENT ,
  LOGIN VARCHAR(30) NOT NULL ,
  FIRSTNAME VARCHAR(30) NOT NULL ,
  LASTNAME VARCHAR(30) NOT NULL ,
  PASSWORD VARCHAR(255) NOT NULL ,
  PRIMARY KEY (ID)
);

CREATE TABLE role (
  ID INT NOT NULL AUTO_INCREMENT ,
  NAME VARCHAR(30) NOT NULL ,
  PRIMARY KEY (ID)
);

CREATE TABLE users_roles (
  USER_ID INT NOT NULL ,
  ROLE_ID INT NOT NULL ,
  PRIMARY KEY (USER_ID, ROLE_ID) ,
  CONSTRAINT FK_USERROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES role (ID) ,
  CONSTRAINT  FK_USERROLE_USER FOREIGN KEY (USER_ID) REFERENCES user (ID)
);

CREATE TABLE privilege (
  ID INT NOT NULL AUTO_INCREMENT ,
  NAME VARCHAR(30) NOT NULL ,
  PRIMARY KEY (ID)
);

CREATE TABLE roles_privileges (
  ROLE_ID INT NOT NULL ,
  PRIVILEGE_ID INT NOT NULL ,
  PRIMARY KEY (ROLE_ID, PRIVILEGE_ID) ,
  CONSTRAINT FK_ROLEPRIVILEGE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES role (ID) ,
  CONSTRAINT FK_ROLEPRIVILEGE_PRIVILAGE FOREIGN KEY (PRIVILEGE_ID) REFERENCES privilege (ID)
);

