DROP TABLE IF EXISTS role_privilege;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS entrance;
DROP TABLE IF EXISTS address;
DROP TABLE IF EXISTS privilege;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS user;

CREATE TABLE address (
  ID INT NOT NULL AUTO_INCREMENT ,
  STREET VARCHAR(30) NOT NULL ,
  HOUSE INT NOT NULL ,
  BUILDING INT NOT NULL ,
  VERSION INT NOT NULL DEFAULT 0 ,
  PRIMARY KEY (ID)
);

CREATE TABLE entrance (
  ID INT NOT NULL AUTO_INCREMENT ,
  ADDRESS_ID INT NOT NULL ,
  NUMBER INT NOT NULL ,
  ACCESS VARCHAR(255) ,
  VERSION INT NOT NULL DEFAULT 0 ,
  PRIMARY KEY (ID) ,
  CONSTRAINT FK_ENTRANCE_1 FOREIGN KEY (ADDRESS_ID) REFERENCES address (ID)
);

CREATE TABLE comment (
  ID INT NOT NULL  AUTO_INCREMENT ,
  MESSAGE VARCHAR(255) NOT NULL ,
  VERSION INT NOT NULL DEFAULT 0 ,
  ENTRANCE_ID INT NOT NULL ,
  PRIMARY KEY (ID) ,
  CONSTRAINT FK_COMMENT_1 FOREIGN KEY (ENTRANCE_ID) REFERENCES entrance (ID)
);

CREATE TABLE user (
  ID INT NOT NULL AUTO_INCREMENT ,
  LOGIN VARCHAR(30) NOT NULL ,
  FIRSTNAME VARCHAR(30) NOT NULL ,
  LASTNAME VARCHAR(30) NOT NULL ,
  PASSWORD VARCHAR(255) NOT NULL ,
  PRIMARY KEY (ID)
);

CREATE TABLE role (
  ID INT NOT NULL AUTO_INCREMENT ,
  NAME VARCHAR(30) NOT NULL ,
  PRIMARY KEY (ID)
);

CREATE TABLE users_roles (
  USER_ID INT NOT NULL ,
  ROLE_ID INT NOT NULL ,
  PRIMARY KEY (USER_ID, ROLE_ID) ,
  CONSTRAINT FK_USERROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES role (ID) ,
  CONSTRAINT  FK_USERROLE_USER FOREIGN KEY (USER_ID) REFERENCES user (ID)
);

CREATE TABLE privilege (
  ID INT NOT NULL AUTO_INCREMENT ,
  NAME VARCHAR(30) NOT NULL ,
  PRIMARY KEY (ID)
);

CREATE TABLE roles_privileges (
  ROLE_ID INT NOT NULL ,
  PRIVILEGE_ID INT NOT NULL ,
  PRIMARY KEY (ROLE_ID, PRIVILEGE_ID) ,
  CONSTRAINT FK_ROLEPRIVILEGE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES role (ID) ,
  CONSTRAINT FK_ROLEPRIVILEGE_PRIVILAGE FOREIGN KEY (PRIVILEGE_ID) REFERENCES privilege (ID)
);

